project_id = "pgbgwakmsypfqqwnjmgh"

[functions.quiz-start]
verify_jwt = false

[functions.quiz-save-answer]
verify_jwt = false

[functions.quiz-submit]
verify_jwt = false

[functions.quiz-result]
verify_jwt = false

[functions.judge-create]
verify_jwt = true

[functions.judge-login]
verify_jwt = false

[functions.judge-data]
verify_jwt = false

[functions.judge-score]
verify_jwt = false

[functions.public-vote]
verify_jwt = false
