import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import {
  FileText, Mail, ShieldCheck, CalendarDays, Award, Newspaper,
  Plus, Trash2, ArrowUp, ArrowDown, Printer, Send, ChevronRight, ChevronLeft, Home,
} from "lucide-react";
import { toast } from "sonner";
import logo from "@/assets/vicharmanch-logo.jpeg";
import { PDF_ATTRIBUTION_HTML } from "@/lib/attribution";

type DocType = "invitation" | "permission" | "schedule" | "congratulation" | "press";

interface ScheduleRow { date: string; day: string; program: string; time: string; color: string; }

const DOC_META: Record<DocType, { label: string; icon: any; color: string; desc: string }> = {
  invitation:     { label: "निमंत्रण पत्र",   icon: Mail,        color: "from-blue-500 to-indigo-600",   desc: "अधिकृत निमंत्रण पत्र तयार करा" },
  permission:     { label: "परवानगी पत्र",   icon: ShieldCheck, color: "from-emerald-500 to-teal-600",  desc: "अधिकाऱ्यांना अर्ज / परवानगी पत्र" },
  schedule:       { label: "कार्यक्रम पत्रिका", icon: CalendarDays, color: "from-amber-500 to-orange-600", desc: "रंगीत कार्यक्रम पत्रिका बनवा" },
  congratulation: { label: "अभिनंदन पत्र",   icon: Award,       color: "from-pink-500 to-rose-600",     desc: "मानपत्र / अभिनंदन पत्र" },
  press:          { label: "प्रसिद्धीपत्रक",  icon: Newspaper,   color: "from-slate-600 to-slate-800",  desc: "प्रेस नोट / प्रसिद्धीपत्रक" },
};

function esc(s: any) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c]!));
}

const HEADER_HTML = `
  <div class="doc-header">
    <img src="${logo}" alt="logo" />
    <div class="org">
      <h1>भारतरत्न डॉ. बाबासाहेब आंबेडकर विचारमंच</h1>
      <p>बौद्ध नगर, लातूर · vicharmanch1956@gmail.com</p>
    </div>
  </div>
  <div class="divider"></div>`;

const FOOTER_HTML = (refId: string) => `
  <footer class="doc-footer">
    <span>${new Date().toLocaleString("mr-IN")}</span>
    <span class="mid">समता · स्वातंत्र्य · बंधुता · न्याय</span>
    <span>${esc(refId)}</span>
  </footer>
  <p class="gen-by">Generated by Vicharmanch Community Operating System</p>
  ${PDF_ATTRIBUTION_HTML}`;

const BASE_CSS = `
  @page { size: A4; margin: 18mm 16mm; }
  * { box-sizing: border-box; -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
  html, body { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
  body { font-family: 'Tiro Devanagari Marathi', 'Noto Sans Devanagari', serif; color:#1e293b; margin:0; padding:0; line-height:1.7; }
  .doc-header { display:flex; align-items:center; gap:14px; padding-bottom:10px; border-bottom:3px solid #1e3a8a; }
  .doc-header img { height:70px; width:70px; object-fit:contain; }
  .org h1 { margin:0; font-size:19px; color:#1e3a8a; }
  .org p { margin:2px 0 0; font-size:12px; color:#475569; }
  .divider { height:4px; background: linear-gradient(90deg,#1e3a8a,#f59e0b,#1e3a8a); border-radius:2px; margin: 8px 0 18px; }
  .ref { text-align:right; font-size:11px; color:#64748b; margin-bottom:6px; }
  .date-line { text-align:right; font-size:13px; margin-bottom:14px; }
  .to { font-size:14px; margin-bottom:14px; white-space:pre-line; }
  .subject { font-weight:700; font-size:14px; margin: 8px 0 12px; border-bottom:1px dashed #cbd5e1; padding-bottom:4px; }
  .salutation { margin-bottom:8px; }
  .body { text-align:justify; font-size:13.5px; text-indent: 24px; white-space:pre-line; }
  .sign { margin-top:36px; text-align:right; }
  .sign .who { font-weight:700; color:#1e3a8a; }
  .sign .org2 { font-size:12px; color:#475569; }
  .doc-footer { position: fixed; bottom: 8mm; left: 16mm; right: 16mm; display:flex; justify-content:space-between; font-size:10px; color:#64748b; border-top:1px solid #cbd5e1; padding-top:4px; }
  .doc-footer .mid { text-align:center; flex:1; font-weight:600; color:#1e3a8a; }
  .gen-by { text-align:center; font-size:9px; color:#94a3b8; margin-top:6px; }
  .press-title { text-align:center; font-size:22px; font-weight:800; color:#1e3a8a; letter-spacing:1px; border:2px solid #1e3a8a; padding:8px; margin: 8px 0 14px; }
  .cong-title { text-align:center; font-size:26px; font-weight:800; color:#b45309; letter-spacing:2px; margin: 12px 0; }
  .cong-name { text-align:center; font-size:22px; font-weight:700; color:#1e3a8a; margin: 6px 0 14px; }
  .schedule-title { text-align:center; font-size:22px; font-weight:800; color:#1e3a8a; margin: 8px 0 14px; }
  table.sched { width:100%; border-collapse: collapse; font-size:14px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  table.sched th { background:#1e3a8a; color:#fff; padding:10px; text-align:left; }
  table.sched td { padding:10px; border-bottom:1px solid #e2e8f0; }
`;

function buildRefId() {
  return `VM-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 900) + 100)}`;
}

const DocumentStudio = () => {
  const [step, setStep] = useState(1);
  const [docType, setDocType] = useState<DocType>("invitation");

  // Shared fields
  const [date, setDate] = useState(new Date().toLocaleDateString("mr-IN", { day: "numeric", month: "long", year: "numeric" }));
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("");
  const [officer, setOfficer] = useState(""); // permission only
  const [salutation, setSalutation] = useState("महोदय,");
  const [body, setBody] = useState("");
  const [signer, setSigner] = useState("आपला विश्वासू\nविचारमंच कार्यकारिणी");

  // Schedule
  const [scheduleTitle, setScheduleTitle] = useState("कार्यक्रम पत्रिका");
  const [rows, setRows] = useState<ScheduleRow[]>([
    { date: "", day: "", program: "", time: "", color: "#e0f2fe" },
  ]);

  // Congratulation
  const [congName, setCongName] = useState("");

  // Send
  const [contact, setContact] = useState("");

  const refId = buildRefId();

  const addRow = () => setRows([...rows, { date: "", day: "", program: "", time: "", color: "#fef3c7" }]);
  const removeRow = (i: number) => setRows(rows.filter((_, idx) => idx !== i));
  const moveRow = (i: number, dir: -1 | 1) => {
    const j = i + dir; if (j < 0 || j >= rows.length) return;
    const next = [...rows]; [next[i], next[j]] = [next[j], next[i]]; setRows(next);
  };
  const updateRow = (i: number, k: keyof ScheduleRow, v: string) => {
    const next = [...rows]; next[i] = { ...next[i], [k]: v }; setRows(next);
  };

  const buildPreviewHtml = (): string => {
    let inner = "";
    if (docType === "invitation") {
      inner = `
        <div class="ref">संदर्भ क्र.: ${refId}</div>
        <div class="date-line">दिनांक: ${esc(date)}</div>
        <div class="to">प्रति,\n${esc(to)}</div>
        <div class="subject">विषय: ${esc(subject)}</div>
        <div class="salutation">${esc(salutation)}</div>
        <div class="body">${esc(body)}</div>
        <div class="sign"><div class="who">${esc(signer.split("\n")[0] || "")}</div><div class="org2">${esc(signer.split("\n").slice(1).join(" · "))}</div></div>`;
    } else if (docType === "permission") {
      inner = `
        <div class="ref">संदर्भ क्र.: ${refId}</div>
        <div class="date-line">दिनांक: ${esc(date)}</div>
        <div class="to">प्रति,\n${esc(officer)}\n${esc(to)}</div>
        <div class="subject">विषय: ${esc(subject)}</div>
        <div class="salutation">${esc(salutation)}</div>
        <div class="body">${esc(body)}</div>
        <div class="sign"><div class="who">${esc(signer.split("\n")[0] || "")}</div><div class="org2">${esc(signer.split("\n").slice(1).join(" · "))}</div></div>`;
    } else if (docType === "schedule") {
      inner = `
        <h1 class="schedule-title">${esc(scheduleTitle)}</h1>
        <table class="sched">
          <thead><tr><th style="width:80px">दिनांक</th><th style="width:70px">वार</th><th>कार्यक्रम</th><th style="width:100px">वेळ</th></tr></thead>
          <tbody>
          ${rows.map((r) => `<tr style="background:${r.color}">
            <td>${esc(r.date)}</td><td>${esc(r.day)}</td><td>${esc(r.program)}</td><td>${esc(r.time)}</td>
          </tr>`).join("")}
          </tbody>
        </table>
        <div class="sign"><div class="who">${esc(signer.split("\n")[0] || "")}</div><div class="org2">${esc(signer.split("\n").slice(1).join(" · "))}</div></div>`;
    } else if (docType === "congratulation") {
      inner = `
        <div class="cong-title">✦ अभिनंदन ✦</div>
        <div class="cong-name">${esc(congName)}</div>
        <div class="body" style="text-indent:0;text-align:center;font-size:15px;">${esc(body)}</div>
        <div class="sign" style="text-align:center;margin-top:40px;"><div class="who">${esc(signer.split("\n")[0] || "")}</div><div class="org2">${esc(signer.split("\n").slice(1).join(" · "))}</div></div>`;
    } else {
      inner = `
        <div class="date-line">दिनांक: ${esc(date)}</div>
        <div class="press-title">प्रसिद्धीपत्रक</div>
        <div class="subject" style="text-align:center;">${esc(subject)}</div>
        <div class="body">${esc(body)}</div>
        <div class="sign"><div class="who">${esc(signer.split("\n")[0] || "")}</div><div class="org2">${esc(signer.split("\n").slice(1).join(" · "))}</div></div>`;
    }
    return `<!DOCTYPE html><html lang="mr"><head><meta charset="UTF-8"><title>${esc(DOC_META[docType].label)}</title>
      <style>${BASE_CSS}</style></head><body>${HEADER_HTML}${inner}${FOOTER_HTML(refId)}</body></html>`;
  };

  const printDoc = () => {
    const w = window.open("", "_blank");
    if (!w) { toast.error("Pop-up blocked"); return; }
    const html = buildPreviewHtml().replace("</body>", "<script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body>");
    w.document.write(html); w.document.close();
  };

  const sendMessage = () => {
    if (!contact.trim()) { toast.error("मोबाईल किंवा ईमेल भरा"); return; }
    const msg = `नमस्कार,\n\n"${DOC_META[docType].label}" — ${subject || "विचारमंच कडून"}\n\n${body || ""}\n\n— भारतरत्न डॉ. बाबासाहेब आंबेडकर विचारमंच, लातूर`;
    if (contact.includes("@")) {
      window.open(`mailto:${contact}?subject=${encodeURIComponent(subject || DOC_META[docType].label)}&body=${encodeURIComponent(msg)}`);
    } else {
      window.open(`https://wa.me/${contact.replace(/\D/g, "")}?text=${encodeURIComponent(msg)}`, "_blank");
    }
  };

  return (
    <div className="space-y-4">
      <Card className="border-0 shadow-md">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <FileText className="h-5 w-5 text-primary" /> दस्तऐवज व्यवस्थापन
            <Badge variant="outline" className="ml-2">पायरी {step}/5</Badge>
          </CardTitle>
          <CardDescription>अधिकृत दस्तऐवज तयार करण्यासाठी टप्प्याटप्प्याने पुढे जा</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Progress */}
          <div className="flex gap-1">
            {[1,2,3,4,5].map((s) => (
              <div key={s} className={`h-1.5 flex-1 rounded-full ${s <= step ? "bg-primary" : "bg-muted"}`} />
            ))}
          </div>

          {step === 1 && (
            <div>
              <p className="text-sm font-semibold mb-3">दस्तऐवज प्रकार निवडा:</p>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                {(Object.keys(DOC_META) as DocType[]).map((k) => {
                  const M = DOC_META[k]; const Icon = M.icon; const active = docType === k;
                  return (
                    <button key={k} onClick={() => setDocType(k)}
                      className={`relative rounded-xl border-2 p-4 text-left transition-all ${active ? "border-primary shadow-md scale-[1.02]" : "border-transparent hover:border-muted-foreground/30"}`}>
                      <div className={`absolute inset-0 bg-gradient-to-br ${M.color} opacity-10 rounded-xl`} />
                      <Icon className="h-6 w-6 text-primary relative" />
                      <p className="font-bold text-sm mt-2 relative">{M.label}</p>
                      <p className="text-[11px] text-muted-foreground mt-1 relative">{M.desc}</p>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="space-y-3">
              <p className="text-sm font-semibold">तपशील भरा — {DOC_META[docType].label}</p>
              {docType !== "schedule" && docType !== "congratulation" && (
                <>
                  <Field label="दिनांक" v={date} on={setDate} />
                  {docType === "permission" && <Field label="अधिकारी" v={officer} on={setOfficer} placeholder="मा. तहसीलदार साहेब" />}
                  <Field label="प्रति (पत्ता)" v={to} on={setTo} multi placeholder={"पूर्ण नाव\nपदनाम\nसंस्था / गाव"} />
                  <Field label="विषय" v={subject} on={setSubject} />
                  <Field label={docType === "press" ? "मुख्य मजकूर" : "मुख्य मजकूर (महोदय...)"} v={body} on={setBody} multi rows={8} />
                </>
              )}
              {docType === "congratulation" && (
                <>
                  <Field label="अभिनंदनासाठी नाव" v={congName} on={setCongName} />
                  <Field label="अभिनंदनाचा मजकूर" v={body} on={setBody} multi rows={6} />
                </>
              )}
              {docType === "schedule" && (
                <>
                  <Field label="पत्रिका शीर्षक" v={scheduleTitle} on={setScheduleTitle} />
                  <div className="space-y-2 rounded-lg border p-3 bg-muted/30">
                    <div className="flex items-center justify-between">
                      <Label className="text-xs font-semibold">कार्यक्रम पंक्ती</Label>
                      <Button size="sm" variant="secondary" onClick={addRow}><Plus className="h-3.5 w-3.5 mr-1" />पंक्ती जोडा</Button>
                    </div>
                    {rows.map((r, i) => (
                      <div key={i} className="grid grid-cols-12 gap-1.5 items-center rounded-md border p-2" style={{ background: r.color }}>
                        <Input className="col-span-2 h-8 text-xs" placeholder="दिनांक" value={r.date} onChange={(e) => updateRow(i, "date", e.target.value)} />
                        <Input className="col-span-2 h-8 text-xs" placeholder="वार" value={r.day} onChange={(e) => updateRow(i, "day", e.target.value)} />
                        <Input className="col-span-4 h-8 text-xs" placeholder="कार्यक्रम" value={r.program} onChange={(e) => updateRow(i, "program", e.target.value)} />
                        <Input className="col-span-2 h-8 text-xs" placeholder="वेळ" value={r.time} onChange={(e) => updateRow(i, "time", e.target.value)} />
                        <input type="color" className="col-span-1 h-8 w-full rounded border" value={r.color} onChange={(e) => updateRow(i, "color", e.target.value)} />
                        <div className="col-span-1 flex gap-0.5">
                          <button onClick={() => moveRow(i, -1)} className="p-1 hover:bg-white/50 rounded"><ArrowUp className="h-3 w-3" /></button>
                          <button onClick={() => moveRow(i, 1)} className="p-1 hover:bg-white/50 rounded"><ArrowDown className="h-3 w-3" /></button>
                          <button onClick={() => removeRow(i)} className="p-1 hover:bg-white/50 rounded text-destructive"><Trash2 className="h-3 w-3" /></button>
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              )}
              <Field label="स्वाक्षरी (पहिली ओळ = नाव)" v={signer} on={setSigner} multi rows={3} />
            </div>
          )}

          {step === 3 && (
            <div className="rounded-lg border p-6 bg-muted/30 text-center space-y-2">
              <p className="text-sm text-muted-foreground">इमेज व लोगो पुढील आवृत्तीत सक्षम केले जातील. लोगो आपोआप वापरला जातो.</p>
              <p className="text-xs">तुम्ही आता थेट पूर्वावलोकनाकडे जाऊ शकता →</p>
            </div>
          )}

          {step === 4 && (
            <div>
              <p className="text-sm font-semibold mb-2">A4 पूर्वावलोकन</p>
              <div className="rounded-lg border overflow-hidden bg-white shadow-inner">
                <iframe title="preview" srcDoc={buildPreviewHtml()} className="w-full h-[70vh] bg-white" />
              </div>
            </div>
          )}

          {step === 5 && (
            <div className="space-y-4">
              <div className="rounded-lg border p-4 bg-emerald-50/50">
                <p className="font-semibold text-emerald-800 mb-2">✅ दस्तऐवज तयार आहे</p>
                <p className="text-sm text-muted-foreground">PDF डाउनलोड करा किंवा थेट प्राप्तकर्त्याला पाठवा.</p>
                <Button className="mt-3 w-full" onClick={printDoc}>
                  <Printer className="h-4 w-4 mr-2" /> PDF / प्रिंट करा
                </Button>
              </div>
              <div className="rounded-lg border p-4">
                <p className="text-sm font-semibold mb-2">📩 प्राप्तकर्त्याला पाठवा (वैकल्पिक)</p>
                <div className="flex gap-2">
                  <Input placeholder="मोबाईल किंवा ईमेल" value={contact} onChange={(e) => setContact(e.target.value)} />
                  <Button onClick={sendMessage}><Send className="h-4 w-4 mr-1" /> पाठवा</Button>
                </div>
                <p className="text-[11px] text-muted-foreground mt-1">मोबाईल → WhatsApp · ईमेल → डिफॉल्ट क्लायंट</p>
              </div>
            </div>
          )}

          <div className="flex justify-between pt-2 border-t">
            <Button variant="outline" onClick={() => setStep(Math.max(1, step - 1))} disabled={step === 1}>
              <ChevronLeft className="h-4 w-4 mr-1" /> मागे
            </Button>
            {step < 5 ? (
              <Button onClick={() => setStep(step + 1)}>पुढे <ChevronRight className="h-4 w-4 ml-1" /></Button>
            ) : (
              <Button variant="secondary" onClick={() => setStep(1)}><Home className="h-4 w-4 mr-1" />नवीन</Button>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

const Field = ({ label, v, on, multi, rows, placeholder }: {
  label: string; v: string; on: (s: string) => void; multi?: boolean; rows?: number; placeholder?: string;
}) => (
  <div className="space-y-1.5">
    <Label className="text-xs">{label}</Label>
    {multi ? (
      <Textarea rows={rows || 4} value={v} onChange={(e) => on(e.target.value)} placeholder={placeholder} />
    ) : (
      <Input value={v} onChange={(e) => on(e.target.value)} placeholder={placeholder} />
    )}
  </div>
);

export default DocumentStudio;
